language: node_js
node_js:
    - "6"
    - "6.1"
services:
    - mongodb
env:
    - MONGODB_URI=mongodb://localhost/test
notifications:
  slack: team4159:wKcqUG4VCrh6yzknuOcvJaf9
script:
    - npm run cover
after_success:
    - bash <(curl -s https://codecov.io/bash)
